### ISSUE TITLE
hacktoberfest

### ISSUE THREAD

**Issue by code1511** [ankur016/DSA-Hactoberfest#2]
@ankur016   hey can you give the hacktoberfest label to this repo

**Comment by code1511** [comment]
also, give hacktoberfest-accepted label

**Comment by ankur016** [comment]
> also, give hacktoberfest-accepted label

yeah done

**Comment by code1511** [comment]
enable this repo under hacktoberfest too because currently this project not participating in hacktoberfest

**Comment by code1511** [comment]
give me write access to this repo
